[package]
name = "audio-lifesaver"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.14"
mpris = "2.0.0"
notify-rust = "4.7.0"
regex = "1.5.4"
