[package]
name = "audio-lifesaver"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
mpris = "1.1.2"
log = "0.4.14"
regex = "1.5.4"
